### ISSUE TITLE
Failed to activate the atom-license package

### ISSUE THREAD

**Issue by Abdillah** [amerine/atom-license#6]
Step to reproduce:
1. Activate command palette, `Ctrl+Shift+P` 
2. Find one of the license command
3. Apply it, no license appear, only this error

**Atom Version**: 1.0.2
**System**: linux 4.0.6-1-ARCH
**Thrown From**: [atom-license](https://github.com/amerine/atom-license) package, v1.0.0
### Stack Trace

Failed to activate the atom-license package

```
At Cannot read property 'command' of undefined

TypeError: Cannot read property 'command' of undefined
  at Object.module.exports.activate (/home/abdillah/.atom/packages/atom-license/lib/atom-license.coffee:3:24)
  at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:240:19)
  at /usr/share/atom/resources/app.asar/src/package.js:772:25
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:222:20)
  at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/usr/share/atom/resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:159:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
  at space-pen-div.atom.commands.add.core:confirm (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:241:29)
  at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/usr/share/atom/resources/app.asar/src/window-event-handler.js:177:20)

```
### Commands

```
     -2:06.6.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -2:01.6.0 core:save (atom-text-editor.editor.is-focused)
     -1:58.6.0 deprecation-cop:view (atom-workspace.workspace.scrollbars-visible-always.theme-base16-tomorrow-dark-theme.theme-one-dark-ui)
     -0:30.9.0 command-palette:toggle (atom-text-editor.editor.is-focused)
 14x -0:28.7.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:21.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:21.4.0 application:show-preferences (atom-text-editor.editor)
     -0:08.3.0 command-palette:toggle (button.btn.icon.enablement.icon-playback-pause)
     -0:07.3.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:07.3.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:05.6.0 project-find:show (atom-text-editor.editor.is-focused)
     -0:04.3.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:04.3.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:03.3.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:00.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:00.5.0 license:MIT (atom-text-editor.editor)
```
### Config

``` json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "base16-tomorrow-dark-theme"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-html-preview, v0.1.9
atom-license, v1.0.0
autoclose-html, v0.18.0
autocomplete-clang, v0.8.7
language-blade, v0.14.0
pigments, v0.8.4

# Dev
No dev packages
```

**Comment by malonehedges** [comment]
I am having this issue as well.

**Comment by germanocorrea** [comment]
same here

**Comment by andymememe** [comment]
Same here

**Comment by kstiehl** [comment]
Same here

**Comment by jarrodek** [comment]
And here

**Comment by handicraftsman** [comment]
Same issue, but i see it on package activation, not usage.

**Comment by noisesfromspace** [comment]
Same problem here, 1.5.4 on Arch Linux

**Comment by germanocorrea** [comment]
This was opened in last year's July. Still no updates.

**Comment by saintplay** [comment]
Yep, same here, Arch Linux

**Comment by aknuds1** [comment]
Me too.

**Comment by saintplay** [comment]
Other repository that works properly: [Atom-Oss-Licence](https://github.com/mmk2410/atom-oss-license)

**Comment by germanocorrea** [comment]
Thanks @djap96 ! Seems like this package isn't going to receive any updates, last commit is from 2014!

**Comment by tterb** [comment]
I too received the same error, though it appeared directly after installation.

**Comment by NeoTheThird** [comment]
Grab your pitchforks, everybody!

**Comment by rzblue** [comment]
Have there been any updates on this?

**Comment by germanocorrea** [comment]
@firecrafty I recommend you to follow @saintplay 's recommendation, the [atom-oss-license](https://github.com/mmk2410/atom-oss-license) package.
